closeComment: >
  This issues been automatically closed due to lack of activity. Feel free to re-open it if you ever come back to it.
daysUntilClose: 90
daysUntilStale: 180
exemptAssignees: true
exemptLabels:
  - "high priority"
  - "good first issue"
  - "pinned"
exemptMilestones: true
exemptProjects: false
limitPerRun: 30
markComment: >
  This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contribution and understanding!
onlyLabels: []
staleLabel: stale
