AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - '.git/**/*'
    - 'bin/*'
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 2.5
InternalAffairs/ExampleDescription:
  Include:
    - 'spec/rubocop/cop/**/*.rb'
InternalAffairs/StyleDetectedApiUse:
  Exclude:
    - 'lib/rubocop/cop/mixin/percent_array.rb'
InternalAffairs/UndefinedConfig:
  Exclude:
    - 'lib/rubocop/cop/correctors/**/*.rb'
    - 'lib/rubocop/cop/mixin/**/*.rb'
  Include:
    - 'lib/rubocop/cop/**/*.rb'
Layout/ClassStructure:
  Enabled: true
Layout/EndOfLine:
  EnforcedStyle: lf
Layout/HashAlignment:
  EnforcedColonStyle:
    - key
    - table
  EnforcedHashRocketStyle:
    - key
    - table
Layout/LineLength:
  IgnoredPatterns:
    - !ruby/regexp /\A +(it|describe|context|shared_examples|include_examples|it_behaves_like) ["']/
  Max: 100
Layout/RedundantLineBreak:
  Enabled: true
Layout/TrailingWhitespace:
  AllowInHeredoc: false
Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*.rb'
Lint/InterpolationCheck:
  Exclude:
    - 'spec/**/*.rb'
Lint/UselessAccessModifier:
  MethodCreatingMethods:
    - 'def_matcher'
    - 'def_node_matcher'
Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
    - '**/*.gemspec'
Metrics/ClassLength:
  Exclude:
    - lib/rubocop/config_obsoletion.rb
Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*.rb'
Naming/InclusiveLanguage:
  Exclude:
    - lib/rubocop/cop/naming/inclusive_language.rb
  FlaggedTerms:
    offence:
      Suggestions:
        - offense
Naming/PredicateName:
  MethodDefinitionMacros:
    - define_method
    - define_singleton_method
    - def_node_matcher
    - def_node_search
Performance/CollectionLiteralInLoop:
  Exclude:
    - 'Rakefile'
    - 'spec/**/*.rb'
Performance/EndWith:
  SafeMultiline: false
Performance/StartWith:
  SafeMultiline: false
RSpec/FilePath:
  Exclude:
    - spec/rubocop/cop/internal_affairs/redundant_let_rubocop_config_new_spec.rb
    - spec/rubocop/formatter/junit_formatter_spec.rb
RSpec/MessageSpies:
  EnforcedStyle: receive
RSpec/MultipleMemoizedHelpers:
  Enabled: false
RSpec/NestedGroups:
  Max: 7
RSpec/PredicateMatcher:
  EnforcedStyle: explicit
RSpec/StubbedMock:
  Enabled: false
Style/AccessorGrouping:
  Exclude:
    - lib/rubocop/formatter/base_formatter.rb
    - lib/rubocop/cop/offense.rb
Style/FormatStringToken:
  Exclude:
    - spec/**/*
Style/IpAddresses:
  Exclude:
    - spec/rubocop/cop/style/ip_addresses_spec.rb
inherit_from: .rubocop_todo.yml
require:
  - rubocop/cop/internal_affairs
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rake
