# encoding: utf-8

module Rubocop
  module AutoCorrection
    # Automatically corrects offences generated by the
    # Cop::Style::CharacterLiteral cop.
    # Replaces "?x" with 'x' and "?\n" with "\n"
    class CharacterLiteral
      Registry.register 'CharacterLiteral', new

      def call(corrector, node)
        string = node.loc.expression.source[1..-1]

        if string.length == 1 # normal character
          corrector.replace(node.loc.expression, "'#{string}'")
        elsif string.length == 2 # special character like \n
          corrector.replace(node.loc.expression, %Q("#{string}"))
        end
      end
    end
  end
end
