# encoding: utf-8

module Rubocop
  module AutoCorrection
    # Automatically corrects offences generated by the
    # Cop::Style::StringLiterals cop.
    # Replaces occurrence of " with ' where possible.
    class StringLiterals
      Registry.register 'StringLiterals', new

      def call(corrector, node)
        corrector.replace(node.loc.begin, "'")
        corrector.replace(node.loc.end, "'")
      end
    end
  end
end
