# encoding: utf-8

module Rubocop
  module AutoCorrection
    # Automatically corrects offences generated by the
    # Cop::Style::WhenThen cop.
    # Removes the occurrence of "when b; c" with "when b then c".
    class WhenThen
      Registry.register 'WhenThen', new

      def call(corrector, node)
        corrector.replace(node.loc.begin, ' then')
      end
    end
  end
end
