# encoding: utf-8

module Rubocop
  module AutoCorrection
    # Automatically corrects offences generated by the
    # Cop::Style::WhileUntilDo cop.
    # Removes "do" from multiline while/until statements.
    class WhileUntilDo
      Registry.register 'WhileUntilDo', new

      def call(corrector, node)
        corrector.remove(node.loc.begin)
      end
    end
  end
end
