# frozen_string_literal: true

module RuboCop
  module Cop
    module Lint
      # Checks that `rubocop:disable` directives say why the cops are disabled.
      #
      # A directive can carry an explanation after `--`. Requiring one turns a
      # suppression into a record of a decision, so the next person to read it
      # can tell whether it still applies instead of having to guess.
      #
      # `rubocop:todo` directives are exempt. They are generated by
      # `--auto-gen-config` and `--disable-uncorrectable`, and already say what
      # they are: debt to be paid rather than a decision to defend.
      #
      # This cop is disabled by default, since it is a team policy rather than
      # something every project wants.
      #
      # `AllowedCops` accepts cop names and department names alike, and exempts a
      # directive only when *everything* it disables is on the list. A codebase
      # adopting this cop is usually carrying a pile of `Metrics` disables whose
      # reason is already obvious from the method they sit on, and exempting
      # that one department keeps the requirement pointed at the directives a
      # reader actually needs explained.
      #
      # Listing a cop does not exempt its whole department: a directive that
      # disables `Metrics` is broader than one that disables
      # `Metrics/AbcSize`, and still has to say why.
      #
      # NOTE: This cop is not disabled by a blanket `rubocop:disable all`, nor
      # by disabling the `Lint` department, since those are the directives it
      # most wants to report. It has to be disabled by name.
      #
      # @example
      #   # bad
      #   # rubocop:disable Metrics/AbcSize
      #   def parse(input)
      #   end
      #   # rubocop:enable Metrics/AbcSize
      #
      #   # good
      #   # rubocop:disable Metrics/AbcSize -- mirrors the shape of the grammar
      #   def parse(input)
      #   end
      #   # rubocop:enable Metrics/AbcSize
      #
      # @example AllowedCops: ['Metrics', 'Style/For']
      #   # good - a cop in an exempt department
      #   # rubocop:disable Metrics/AbcSize
      #   def parse(input)
      #   end
      #   # rubocop:enable Metrics/AbcSize
      #
      #   # good - an exempt cop named outright
      #   # rubocop:disable Style/For
      #   for x in [1, 2] do puts x end
      #   # rubocop:enable Style/For
      #
      #   # bad - Style/For is not exempt, so the whole directive needs a reason
      #   # rubocop:disable Metrics/AbcSize, Style/For
      #   def parse(input)
      #   end
      #   # rubocop:enable Metrics/AbcSize, Style/For
      #
      #   # good - todo directives record debt rather than a decision
      #   # rubocop:todo Metrics/AbcSize
      #   def parse(input)
      #   end
      #   # rubocop:enable Metrics/AbcSize
      #
      class MissingCopDisableReason < Base
        MSG = 'Add a `--` comment explaining why the cops are disabled.'

        def on_new_investigation
          processed_source.comments.each do |comment|
            directive = DirectiveComment.new(comment)
            next unless suppressing?(directive)
            next if entirely_allowed?(directive)
            # A broken directive is `Lint/CopDirectiveSyntax`'s business, and
            # the missing reason is rarely the interesting part of it.
            next if directive.malformed? || directive.reason

            add_offense(directive.range)
          end
        end

        private

        # `push` and `next` suppress only the cops they mark with `-`.
        def suppressing?(directive)
          case directive.mode
          when 'disable', 'disable-next' then true
          when 'push', 'next' then directive.signed_args.key?('-')
          else false
          end
        end

        # A directive is exempt only when everything it disables is exempt. One
        # unlisted cop and the reader is owed an explanation for the directive.
        def entirely_allowed?(directive)
          return false if allowed_cops.empty? || directive.all_cops?

          names = disabled_names(directive)

          names.any? && names.all? { |name| allowed?(name) }
        end

        def allowed?(name)
          allowed_cops.include?(name) || allowed_cops.include?(name.split('/').first)
        end

        def disabled_names(directive)
          return directive.raw_cop_names unless directive.push? || directive.next?

          directive.signed_args.fetch('-', [])
        end

        def allowed_cops
          @allowed_cops ||= Array(cop_config['AllowedCops'])
        end
      end
    end
  end
end
