= History

[quote]
You don't know where you're going until you know where you've been.

RuboCop was created by Bozhidar Batsov in the spring of 2012, as an attempt
to make it easy to apply consistently the guidelines from the community Ruby Style Guide.footnote:[This is the https://github.com/rubocop/ruby-style-guide/issues/54[GitHub issue] that started it all.]


== Notable Milestones

* 12 Sep 2011 - Creation of the community Ruby Style Guide.
* 21 Apr 2012 - Initial commit by Bozhidar Batsov.
* 03 May 2012 - RuboCop 0.0.0 is released.
* 28 May 2013 - RuboCop 0.8 is released. It's the first version fully powered by the powerful `parser` gem.
* 01 Jul 2013 - RuboCop 0.9 introduces autocorrection and output formatters.
* 31 May 2018 - At RubyKaigi 2018 Bozhidar announces the transition of the project to a RuboCop GitHub organization. He also outlines the plans for a 1.0 release that guide the next couple of years of development.
* 21 Oct 2020 - RuboCop 1.0 is released (exactly 7.5 years after the first commit).
* 06 Mar 2024 - RuboCop 1.62 adds support for Prism.

== Additional Resources

* https://www.youtube.com/watch?v=nrHjVCuVsGA[All About RuboCop (RubyKaigi 2018)]
* https://metaredux.com/posts/2020/10/21/rubocop-1-0.html[RuboCop 1.0]
* https://metaredux.com/posts/2022/04/21/rubocop-turns-10.html[RuboCop Turns 10]
