changed_enforced_styles:
  - alternative: indented_internal_methods
    cops: Layout/IndentationConsistency
    parameters: EnforcedStyle
    value: rails
changed_parameters:
  - cops:
      - Layout/SpaceAroundOperators
      - Style/SpaceAroundOperators
    parameters: MultiSpaceAllowedForOperators
    reason: >
      If your intention was to allow extra spaces for alignment, please use `AllowForAlignment: true` instead.
  - cops: Style/Encoding
    parameters:
      - EnforcedStyle
      - SupportedStyles
      - AutoCorrectEncodingComment
    reason: '`Style/Encoding` no longer supports styles. The "never" behavior is always assumed.'
  - cops: Style/IfUnlessModifier
    parameters: MaxLineLength
    reason: >
      `Style/IfUnlessModifier: MaxLineLength` has been removed. Use `Layout/LineLength: Max` instead
  - cops: Style/WhileUntilModifier
    parameters: MaxLineLength
    reason: >
      `Style/WhileUntilModifier: MaxLineLength` has been removed. Use `Layout/LineLength: Max` instead
  - cops: AllCops
    parameters: RunRailsCops
    reason: |-
      Use the following configuration instead:
      Rails:
        Enabled: true
  - alternative: EnforcedStyle
    cops: Layout/CaseIndentation
    parameters: IndentWhenRelativeTo
  - alternative: EnforcedStyleAlignWith
    cops:
      - Lint/BlockAlignment
      - Layout/BlockAlignment
      - Lint/EndAlignment
      - Layout/EndAlignment
      - Lint/DefEndAlignment
      - Layout/DefEndAlignment
    parameters: AlignWith
  - alternative: EnforcedStyle
    cops: Rails/UniqBeforePluck
    parameters: EnforcedMode
  - alternative: IgnoredPatterns
    cops: Style/MethodCallWithArgsParentheses
    parameters: IgnoredMethodPatterns
  - cops:
      - Performance/Count
      - Performance/Detect
    parameters: SafeMode
    reason: "`SafeMode` has been removed. Use `SafeAutoCorrect` instead."
  - alternative: IgnoredGems
    cops: Bundler/GemComment
    parameters: Whitelist
  - alternative: AllowedMethods
    cops:
      - Lint/SafeNavigationChain
      - Lint/SafeNavigationConsistency
      - Style/NestedParenthesizedCalls
      - Style/SafeNavigation
      - Style/TrivialAccessors
    parameters: Whitelist
  - alternative: AllowedAddresses
    cops: Style/IpAddresses
    parameters: Whitelist
  - alternative: ForbiddenDelimiters
    cops: Naming/HeredocDelimiterNaming
    parameters: Blacklist
  - alternative: ForbiddenPrefixes
    cops: Naming/PredicateName
    parameters: NamePrefixBlacklist
  - alternative: AllowedMethods
    cops: Naming/PredicateName
    parameters: NameWhitelist
  - alternative: IgnoredMethods
    cops:
      - Metrics/BlockLength
      - Metrics/MethodLength
    parameters: ExcludedMethods
    severity: warning
  - cops: Lint/Debugger
    parameters: DebuggerReceivers
    reason: "`DebuggerReceivers` is no longer necessary, method receivers should be specified in `DebuggerMethods` instead."
    severity: warning
extracted:
  Performance/*: rubocop-performance
  Rails/*: rubocop-rails
removed:
  Layout/SpaceAfterControlKeyword:
    alternatives: Layout/SpaceAroundKeyword
  Layout/SpaceBeforeModifierKeyword:
    alternatives: Layout/SpaceAroundKeyword
  Lint/InvalidCharacterLiteral:
    reason: it was never being actually triggered
  Lint/RescueWithoutErrorClass:
    alternatives: Style/RescueStandardError
  Lint/SpaceBeforeFirstArg:
    reason: >
      it was a duplicate of `Layout/SpaceBeforeFirstArg`. Please use `Layout/SpaceBeforeFirstArg` instead
  Lint/UselessComparison:
    reason: >
      it has been superseded by `Lint/BinaryOperatorWithIdenticalOperands`. Please use `Lint/BinaryOperatorWithIdenticalOperands` instead
  Style/BracesAroundHashParameters: true
  Style/MethodMissingSuper:
    reason: >
      it has been superseded by `Lint/MissingSuper`. Please use `Lint/MissingSuper` instead
  Style/SpaceAfterControlKeyword:
    alternatives: Layout/SpaceAroundKeyword
  Style/SpaceBeforeModifierKeyword:
    alternatives: Layout/SpaceAroundKeyword
  Style/TrailingComma:
    alternatives:
      - Style/TrailingCommaInArguments
      - Style/TrailingCommaInArrayLiteral
      - Style/TrailingCommaInHashLiteral
  Style/TrailingCommaInLiteral:
    alternatives:
      - Style/TrailingCommaInArrayLiteral
      - Style/TrailingCommaInHashLiteral
renamed:
  Layout/AlignArguments: Layout/ArgumentAlignment
  Layout/AlignArray: Layout/ArrayAlignment
  Layout/AlignHash: Layout/HashAlignment
  Layout/AlignParameters: Layout/ParameterAlignment
  Layout/IndentArray: Layout/FirstArrayElementIndentation
  Layout/IndentAssignment: Layout/AssignmentIndentation
  Layout/IndentFirstArgument: Layout/FirstArgumentIndentation
  Layout/IndentFirstArrayElement: Layout/FirstArrayElementIndentation
  Layout/IndentFirstHashElement: Layout/FirstHashElementIndentation
  Layout/IndentFirstParameter: Layout/FirstParameterIndentation
  Layout/IndentHash: Layout/FirstHashElementIndentation
  Layout/IndentHeredoc: Layout/HeredocIndentation
  Layout/LeadingBlankLines: Layout/LeadingEmptyLines
  Layout/Tab: Layout/IndentationStyle
  Layout/TrailingBlankLines: Layout/TrailingEmptyLines
  Lint/BlockAlignment: Layout/BlockAlignment
  Lint/DefEndAlignment: Layout/DefEndAlignment
  Lint/DuplicatedKey: Lint/DuplicateHashKey
  Lint/EndAlignment: Layout/EndAlignment
  Lint/EndInMethod: Style/EndBlock
  Lint/Eval: Security/Eval
  Lint/HandleExceptions: Lint/SuppressedException
  Lint/MultipleCompare: Lint/MultipleComparison
  Lint/StringConversionInInterpolation: Lint/RedundantStringCoercion
  Lint/UnneededCopDisableDirective: Lint/RedundantCopDisableDirective
  Lint/UnneededCopEnableDirective: Lint/RedundantCopEnableDirective
  Lint/UnneededRequireStatement: Lint/RedundantRequireStatement
  Lint/UnneededSplatExpansion: Lint/RedundantSplatExpansion
  Metrics/LineLength: Layout/LineLength
  Naming/UncommunicativeBlockParamName: Naming/BlockParameterName
  Naming/UncommunicativeMethodParamName: Naming/MethodParameterName
  Style/AccessorMethodName: Naming/AccessorMethodName
  Style/AsciiIdentifiers: Naming/AsciiIdentifiers
  Style/ClassAndModuleCamelCase: Naming/ClassAndModuleCamelCase
  Style/ConstantName: Naming/ConstantName
  Style/DeprecatedHashMethods: Style/PreferredHashMethods
  Style/FileName: Naming/FileName
  Style/FlipFlop: Lint/FlipFlop
  Style/MethodCallParentheses: Style/MethodCallWithoutArgsParentheses
  Style/MethodName: Naming/MethodName
  Style/OpMethod: Naming/BinaryOperatorParameterName
  Style/PredicateName: Naming/PredicateName
  Style/SingleSpaceBeforeFirstArg: Layout/SpaceBeforeFirstArg
  Style/UnneededCapitalW: Style/RedundantCapitalW
  Style/UnneededCondition: Style/RedundantCondition
  Style/UnneededInterpolation: Style/RedundantInterpolation
  Style/UnneededPercentQ: Style/RedundantPercentQ
  Style/UnneededSort: Style/RedundantSort
  Style/VariableName: Naming/VariableName
  Style/VariableNumber: Naming/VariableNumber
split:
  Style/MethodMissing:
    alternatives:
      - Style/MethodMissingSuper
      - Style/MissingRespondToMissing
