#!/usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH.unshift("#{__dir__}/../lib")

require 'rubocop'
require 'benchmark'

cli = RuboCop::CLI.new
result = 0

time = Benchmark.realtime { result = cli.run }

puts "Finished in #{time} seconds" if cli.options[:debug] || cli.options[:display_time]
exit result
