# encoding: utf-8

module RuboCop
  module Formatter
    # This formatter displays a YAML configuration file where all cops that
    # detected any offenses are configured to not detect the offense.
    class DisabledConfigFormatter < BaseFormatter
      HEADING =
        ['# This configuration was generated by',
         '# `%s`',
         "# on #{Time.now} using RuboCop version #{Version.version}.",
         '# The point is for the user to remove these configuration records',
         '# one by one as the offenses are removed from the code base.',
         '# Note that changes in the inspected code, or installation of new',
         '# versions of RuboCop, may require this file to be generated again.']
        .join("\n")

      @config_to_allow_offenses = {}

      COPS = Cop::Cop.all.group_by(&:cop_name)

      class << self
        attr_accessor :config_to_allow_offenses
        attr_accessor :exclude_limit
      end

      def file_finished(_file, offenses)
        @cops_with_offenses ||= Hash.new([])
        offenses.each do |o|
          @cops_with_offenses[o.cop_name] += [o.location.source_buffer.name]
        end
      end

      def finished(_inspected_files)
        command = 'rubocop --auto-gen-config'
        exclude_limit = self.class.exclude_limit
        if exclude_limit
          command += format(' --exclude-limit %d', exclude_limit.to_i)
        end
        output.puts HEADING % command
        output.puts '# Offense count per file in parentheses.' if exclude_limit

        # Syntax isn't a real cop and it can't be disabled.
        @cops_with_offenses.delete('Syntax')

        @cops_with_offenses.sort.each do |cop_name, offense_file_names|
          output.puts
          output_cop_config(cop_name, offense_file_names)
        end
        puts "Created #{output.path}."
        puts "Run `rubocop --config #{output.path}`, or"
        puts "add inherit_from: #{output.path} in a .rubocop.yml file."
      end

      def output_cop_config(cop_name, offense_file_names)
        cfg = self.class.config_to_allow_offenses[cop_name]
        cfg ||= { 'Enabled' => false }
        output_cop_comments(output, cfg, cop_name, offense_file_names.size)
        output.puts "#{cop_name}:"
        files = offense_file_names.group_by { |f| PathUtil.relative_path(f) }
        if self.class.exclude_limit &&
           files.size <= self.class.exclude_limit.to_i
          output.puts '  Exclude:'
          files.each do |name, list|
            output.puts "    - '#{name}' # (#{list.size})"
          end
        else
          cfg.each { |key, value| output.puts "  #{key}: #{value}" }
        end
      end

      def output_cop_comments(output, cfg, cop_name, offense_count)
        output.puts "# Offense count: #{offense_count}"
        if COPS[cop_name] && COPS[cop_name].first.new.support_autocorrect?
          output.puts '# Cop supports --auto-correct.'
        end

        default_cfg = RuboCop::ConfigLoader.default_configuration[cop_name]
        return unless default_cfg

        params = default_cfg.keys - %w(Description StyleGuide Enabled) -
                 cfg.keys
        return if params.empty?

        output.puts "# Configuration parameters: #{params.join(', ')}."
      end
    end
  end
end
