#!/usr/bin/env ruby
# frozen_string_literal: true

# Estimate how often each RuboCop cop is disabled by end users, using GitHub's
# code search API as the data source.
#
# For every cop in the loaded registry it counts how many public files contain
# an inline suppression directive for that cop:
#
#   rubocop:disable Department/CopName   # deliberate, per-line suppression
#   rubocop:todo    Department/CopName   # suppression generated by --auto-gen-config
#
# The two together are a good proxy for "users actively turn this cop off".
# (Wholesale `Enabled: false` config disables are deliberately *not* counted:
# GitHub code search can't reliably scope a phrase to a `.rubocop.yml` file, so
# any such number would be noise. See REPORT for the methodology discussion.)
#
# The script is incremental and resumable: every result is written to a JSON
# cache keyed by "Cop|pattern", so re-running only fetches what is missing. Kill
# it any time and start it again; it picks up where it left off.
#
# Auth + transport go through the `gh` CLI (`gh api`), so you just need to be
# logged in with `gh auth login`. Code search is limited to 10 requests/minute,
# so a full run over ~600 cops and 2 patterns takes ~2 hours. That's expected.
#
# Usage:
#   ruby tools/cop_disable_stats.rb                 # collect, then write report
#   ruby tools/cop_disable_stats.rb --report-only   # just regenerate report from cache
#   ruby tools/cop_disable_stats.rb --patterns disable
#   ruby tools/cop_disable_stats.rb --limit 50      # only the first N cops (smoke test)
#   ruby tools/cop_disable_stats.rb --cops Style/Documentation,Metrics/AbcSize --patterns todo
#
# Outputs (under tmp/ by default):
#   tmp/cop-disable-stats.json   raw cache (counts per cop/pattern)
#   tmp/cop-disable-stats.md     ranked Markdown report
#   tmp/cop-disable-stats.csv    same data as CSV

require 'json'
require 'open3'
require 'optparse'

module CopDisableStats
  # Each pattern is a labelled phrase template. `%<cop>s` is the full cop name.
  PATTERNS = {
    'disable' => 'rubocop:disable %<cop>s',
    'todo' => 'rubocop:todo %<cop>s'
  }.freeze

  # Seconds to wait between code-search calls. The limit is 10/min; 6.5s keeps us
  # comfortably under it without tripping the secondary abuse limiter.
  THROTTLE_SECONDS = 6.5

  class Collector
    attr_reader :cache_path, :patterns, :cache

    def initialize(cache_path:, patterns:)
      @cache_path = cache_path
      @patterns = patterns
      @cache = File.exist?(cache_path) ? JSON.parse(File.read(cache_path)) : {}
    end

    def collect(cops)
      pending = cops.product(patterns.keys).reject { |cop, pat| cache.key?(key(cop, pat)) }
      total = pending.size
      if total.zero?
        warn "Nothing to fetch; #{cache.size} entries already cached."
        return
      end

      warn "Fetching #{total} (cop, pattern) counts (~#{(total * THROTTLE_SECONDS / 60).ceil} min)..."
      pending.each_with_index do |(cop, pat), i|
        count = search_count(format(patterns[pat], cop: cop))
        cache[key(cop, pat)] = count
        persist
        warn format('[%4d/%-4d] %-7s %-45s %s', i + 1, total, pat, cop, count || 'ERR')
        sleep(THROTTLE_SECONDS) unless i == total - 1
      end
    end

    private

    def key(cop, pattern) = "#{cop}|#{pattern}"

    def persist
      File.write(cache_path, JSON.pretty_generate(cache))
    end

    # Returns the total_count for an exact-phrase code search, or nil on failure.
    # Retries with backoff on transient/secondary-rate-limit errors.
    def search_count(phrase, attempt: 1)
      q = %("#{phrase}")
      stdout, stderr, status = Open3.capture3('gh', 'api', '-X', 'GET', 'search/code',
                                              '-f', "q=#{q}", '--jq', '.total_count')
      return Integer(stdout.strip) if status.success? && stdout.strip =~ /\A\d+\z/

      if attempt <= 5 && (stderr =~ /rate limit|abuse|secondary|HTTP 4/i || stdout.empty?)
        backoff = attempt * 30
        warn "  retry #{attempt} in #{backoff}s (#{stderr.strip[0, 80]})"
        sleep(backoff)
        return search_count(phrase, attempt: attempt + 1)
      end

      warn "  giving up on #{phrase.inspect}: #{stderr.strip[0, 120]}"
      nil
    end
  end

  class Report
    def initialize(cache:, patterns:)
      @cache = cache
      @patterns = patterns
    end

    # => [{ cop:, dept:, counts: { 'disable' => n, ... }, total: n }, ...]
    def rows
      cops = @cache.keys.map { |k| k.split('|').first }.uniq
      cops.map do |cop|
        counts = @patterns.keys.to_h { |pat| [pat, @cache["#{cop}|#{pat}"]] }
        total = counts.values.compact.sum
        { cop: cop, dept: cop.split('/').first, counts: counts, total: total }
      end.sort_by { |r| -r[:total] }
    end

    def to_markdown
      ranked = rows
      out = +"# Most-disabled RuboCop cops (GitHub inline-suppression counts)\n\n"
      out << "Source: GitHub code search `total_count` of files containing each directive.\n"
      out << "Generated by `tools/cop_disable_stats.rb`. Counts are public-file estimates, "
      out << "not exact, and undercount autocorrectable/config-toggled cops (see report notes).\n\n"
      out << department_summary(ranked)
      out << "\n## Top 75 cops by total inline suppressions\n\n"
      header = ['#', 'Cop'] + @patterns.keys.map(&:capitalize) + ['Total']
      out << "| #{header.join(' | ')} |\n"
      out << "|#{(['---'] * header.size).join('|')}|\n"
      ranked.first(75).each_with_index do |r, i|
        cols = [i + 1, "`#{r[:cop]}`"] + @patterns.keys.map { |p| r[:counts][p] || '-' } + [r[:total]]
        out << "| #{cols.join(' | ')} |\n"
      end
      out
    end

    def to_csv
      out = +(['cop', 'department', *@patterns.keys, 'total'].join(',') + "\n")
      rows.each do |r|
        out << ([r[:cop], r[:dept], *@patterns.keys.map { |p| r[:counts][p] }, r[:total]].join(',') + "\n")
      end
      out
    end

    private

    def department_summary(ranked)
      by_dept = ranked.group_by { |r| r[:dept] }
                      .transform_values { |rs| rs.sum { |r| r[:total] } }
                      .sort_by { |_, v| -v }
      out = +"## By department (sum of suppressions)\n\n| Department | Total | Cops covered |\n|---|---|---|\n"
      by_dept.each do |dept, total|
        out << "| #{dept} | #{total} | #{ranked.count { |r| r[:dept] == dept }} |\n"
      end
      out
    end
  end

  module_function

  def cop_names
    require 'rubocop'
    RuboCop::Cop::Registry.global.cops.map(&:cop_name).sort
  rescue LoadError
    abort 'Could not load rubocop. Run me from a checkout with `bundle exec`.'
  end

  def run(argv)
    opts = {
      cache: 'tmp/cop-disable-stats.json',
      report_md: 'tmp/cop-disable-stats.md',
      report_csv: 'tmp/cop-disable-stats.csv',
      patterns: PATTERNS.keys,
      limit: nil,
      cops: nil,
      report_only: false
    }
    OptionParser.new do |o|
      o.on('--cache FILE') { |v| opts[:cache] = v }
      o.on('--patterns LIST', 'comma list: disable,todo') { |v| opts[:patterns] = v.split(',') }
      o.on('--limit N', Integer, 'only first N cops') { |v| opts[:limit] = v }
      o.on('--cops LIST', 'comma list of specific cops to fetch') { |v| opts[:cops] = v.split(',') }
      o.on('--report-only', 'regenerate report from cache, no fetching') { opts[:report_only] = true }
    end.parse!(argv)

    patterns = PATTERNS.slice(*opts[:patterns])
    abort "Unknown patterns: #{opts[:patterns]}" if patterns.empty?

    unless opts[:report_only]
      cops = opts[:cops] || cop_names
      cops = cops.first(opts[:limit]) if opts[:limit]
      Collector.new(cache_path: opts[:cache], patterns: patterns).collect(cops)
    end

    cache = JSON.parse(File.read(opts[:cache]))
    report = Report.new(cache: cache, patterns: patterns)
    File.write(opts[:report_md], report.to_markdown)
    File.write(opts[:report_csv], report.to_csv)
    warn "Wrote #{opts[:report_md]} and #{opts[:report_csv]} (#{cache.size} cached entries)."
  end
end

CopDisableStats.run(ARGV) if $PROGRAM_NAME == __FILE__
